#config/routes.yaml

homepage:
  path: /
  prefix: homepage
  controller: App\Controller\BlogController::index

article_create:
  path: /new
  prefix: article_create
  controller: App\Controller\BlogController::new

article_show:
  path: /show/{id}
  controller: App\Controller\BlogController::show

article_edit: 
  path: /edit/{id}
  controller: App\Controller\BlogController::edit
  requirements:
    id: '\d+'

article_remove:
  path: /remove/{id}
  controller: App\Controller\BlogController::remove
  requirements:
    id: '\d+'

admin_login:
  path: /admin
  prefix: admin_login
  controller: App\Controller\SecurityController::connexion   